<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:err="urn:be:fgov:ehealth:errors:soa:v1" xmlns:kgss="urn:be:fgov:ehealth:etee:kgss:1_0:protocol" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:types="urn:be:fgov:ehealth:etee:kgss:1_0:protocol" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="Kgss" targetNamespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol">
  <documentation>Key Generation Storage Service - version 1.3</documentation>
  <types>
    <xs:schema>
      <xs:import namespace="urn:be:fgov:ehealth:etee:kgss:1_0:protocol" schemaLocation="../XSD/ehealth-etee-kgss-schema-protocol-1_3.xsd"/>
      <xs:import namespace="urn:be:fgov:ehealth:errors:soa:v1" schemaLocation="../../ehealth-errors/XSD/ehealth-errors-schema-soa-1_1.xsd"/>
    </xs:schema>
  </types>
  <message name="GetNewKeyRequestMessage">
    <part element="types:GetNewKeyRequest" name="body"/>
  </message>
  <message name="GetNewKeyResponseMessage">
    <part element="types:GetNewKeyResponse" name="body"/>
  </message>
  <message name="GetKeyRequestMessage">
    <part element="types:GetKeyRequest" name="body"/>
  </message>
  <message name="GetKeyResponseMessage">
    <part element="types:GetKeyResponse" name="body"/>
  </message>
  <wsdl:message name="SystemError">
    <wsdl:part element="err:SystemError" name="fault"/>
  </wsdl:message>
  <portType name="KgssPortType">
    <operation name="GetNewKey">
      <input message="kgss:GetNewKeyRequestMessage"/>
      <output message="kgss:GetNewKeyResponseMessage"/>
      <wsdl:fault message="kgss:SystemError" name="SystemError"/>
    </operation>
    <operation name="GetKey">
      <input message="kgss:GetKeyRequestMessage"/>
      <output message="kgss:GetKeyResponseMessage"/>
      <wsdl:fault message="kgss:SystemError" name="SystemError"/>
    </operation>
  </portType>
  <binding name="KgssSoapBinding" type="kgss:KgssPortType">
    <soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetNewKey">
      <soap11:operation soapAction=""/>
      <input>
        <soap11:body use="literal"/>
      </input>
      <output>
        <soap11:body use="literal"/>
      </output>
      <wsdl:fault name="SystemError">
        <soap11:fault name="SystemError" use="literal"/>
      </wsdl:fault>
    </operation>
    <operation name="GetKey">
      <soap11:operation soapAction=""/>
      <input>
        <soap11:body use="literal"/>
      </input>
      <output>
        <soap11:body use="literal"/>
      </output>
      <wsdl:fault name="SystemError">
        <soap11:fault name="SystemError" use="literal"/>
      </wsdl:fault>
    </operation>
  </binding>
  <service name="KgssService">
    <port binding="kgss:KgssSoapBinding" name="KgssPort">
      <soap11:address location="https://services.ehealth.fgov.be/Kgss/v1"/>
    </port>
  </service>
</definitions>
