<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:dss="urn:oasis:names:tc:dss:1.0:core:schema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:be:fgov:ehealth:timestamping:protocol:v2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:be:fgov:ehealth:timestamping:protocol:v2">
  <documentation>Version 2.2 : web service definition for Timestamping authority</documentation>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="X509">
    <sp:AsymmetricBinding>
      <wsp:Policy>
        <sp:InitiatorToken>
          <wsp:Policy>
            <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssX509V3Token10/>
              </wsp:Policy>
            </sp:X509Token>
          </wsp:Policy>
        </sp:InitiatorToken>
        <sp:RecipientToken>
          <wsp:Policy>
            <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
              <wsp:Policy>
                <sp:WssX509V3Token10/>
              </wsp:Policy>
            </sp:X509Token>
          </wsp:Policy>
        </sp:RecipientToken>
        <sp:AlgorithmSuite>
          <wsp:Policy>
            <sp:Basic256/>
          </wsp:Policy>
        </sp:AlgorithmSuite>
        <sp:Layout>
          <wsp:Policy>
            <sp:Lax/>
          </wsp:Policy>
        </sp:Layout>
        <sp:IncludeTimestamp/>
        <sp:ProtectTokens/>
        <sp:OnlySignEntireHeadersAndBody/>
      </wsp:Policy>
    </sp:AsymmetricBinding>
    <sp:Wss10>
      <wsp:Policy>
        <sp:MustSupportRefKeyIdentifier/>
        <sp:MustSupportRefIssuerSerial/>
      </wsp:Policy>
    </sp:Wss10>
    <sp:SignedParts>
      <sp:Body/>
    </sp:SignedParts>
  </wsp:Policy>
  <types>
    <xsd:schema targetNamespace="urn:oasis:names:tc:dss:1.0:core:schema:xsd">
      <xsd:import namespace="urn:oasis:names:tc:dss:1.0:core:schema" schemaLocation="../../external/XSD/oasis-dss-core-schema-v1.0-os.xsd"/>
    </xsd:schema>
  </types>
  <message name="stamp">
    <part element="dss:SignRequest" name="signRequest"/>
  </message>
  <message name="stampResponse">
    <part element="dss:SignResponse" name="result"/>
  </message>
  <portType name="timestampauthorityPort">
    <operation name="stamp">
      <input message="tns:stamp"/>
      <output message="tns:stampResponse"/>
    </operation>
  </portType>
  <binding name="timestampauthorityPort" type="tns:timestampauthorityPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="stamp">
      <soap:operation soapAction="urn:be:fgov:ehealth:timestamping:protocol:v2:stamp" style="document"/>
      <input>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#X509"/>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="TimeStampAuthority">
    <port binding="tns:timestampauthorityPort" name="timestampauthorityPort">
      <soap:address location="https://services.ehealth.fgov.be/TimestampAuthority/v2"/>
    </port>
  </service>
</definitions>
